tunnel: YOUR_TUNNEL_ID
credentials-file: /home/YOUR_LINUX_USER/.cloudflared/YOUR_TUNNEL_ID.json

ingress:
  - hostname: YOUR_APP_HOSTNAME
    service: http://localhost:4187
  - service: http_status:404
